services:
    skouat.ppde.api.paypal.client_factory:
        class: skouat\ppde\api\paypal\client_factory
        arguments:
            - '@config'
            - '@language'

    skouat.ppde.api.paypal.system_check:
        class: skouat\ppde\api\paypal\system_check
        arguments:
            - '@config'
            - '@skouat.ppde.extension_manager'

    skouat.ppde.api.paypal.webhook_verify:
        class: skouat\ppde\api\paypal\webhook_verify
        arguments:
            - '@cache.driver'
            - '@config'
