skouat_ppde_donate:
    path: /donate
    defaults: { _controller: skouat.ppde.controller.main.donate:handle }
skouat_ppde_donorlist:
    path: /donorlist
    defaults: { _controller: skouat.ppde.controller.main.donorlist:handle }
skouat_ppde_ipn_listener:
    path: /ipn-listener
    defaults: { _controller: skouat.ppde.ipn_listener:handle }
skouat_ppde_create_order:
    path: /donate/create-order
    defaults: { _controller: skouat.ppde.controller.order:create }
skouat_ppde_capture_order:
    path: /donate/capture-order
    defaults: { _controller: skouat.ppde.controller.order:capture }
skouat_ppde_webhook:
    path: /donate/webhook
    defaults: { _controller: skouat.ppde.webhook_listener:handle }
